language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
after_success: npm run coverage
env:
  - DATABASE_NAME=bank_test DATABASE_URL=postgres://localhost:5432/bank_test
services:
  - postgresql
before_script:
  - psql -c 'create database bank_test;' -U postgres
