language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
after_success: npm run coverage
env:
  - DATABASE_NAME=bank_test DATABASE_URL=postgres://localhost:5432/$DATABASE_NAME
services:
  - postgresql
before_script:
  - env DATABASE_NAME=bank_test npm run create-db
